image:
  registry: us-central1-docker.pkg.dev/online-boutique-ci/microservices-demo
  tag: v0.10.6
  pullPolicy: IfNotPresent

# Service DNS names. Must match the Service metadata.name you emit.
frontendEnv:
  PORT: "8080"
  PRODUCT_CATALOG_SERVICE_ADDR: "productcatalogservice:3550"
  CURRENCY_SERVICE_ADDR: "currencyservice:7000"
  CART_SERVICE_ADDR: "cartservice:7070"
  RECOMMENDATION_SERVICE_ADDR: "recommendationservice:8080"
  SHIPPING_SERVICE_ADDR: "shippingservice:50051"
  CHECKOUT_SERVICE_ADDR: "checkoutservice:5050"
  AD_SERVICE_ADDR: "adservice:9555"
  SHOPPING_ASSISTANT_SERVICE_ADDR: "shoppingassistantservice:80"
  ENABLE_PROFILER: "0"

checkoutEnv:
  PORT: "5050"
  PRODUCT_CATALOG_SERVICE_ADDR: "productcatalogservice:3550"
  SHIPPING_SERVICE_ADDR: "shippingservice:50051"
  PAYMENT_SERVICE_ADDR: "paymentservice:50051"
  EMAIL_SERVICE_ADDR: "emailservice:5000"
  CURRENCY_SERVICE_ADDR: "currencyservice:7000"
  CART_SERVICE_ADDR: "cartservice:7070"

services:
  frontend:
    replicas: 1
    containerPort: 8080
    servicePort: 80          # ClusterIP 80 -> container 8080
    type: ClusterIP
  cartservice:
    replicas: 1
    containerPort: 7070
    servicePort: 7070
    env:
      REDIS_ADDR: "redis-cart:6379"
  productcatalogservice:
    replicas: 1
    containerPort: 3550
    servicePort: 3550
  currencyservice:
    replicas: 1
    containerPort: 7000
    servicePort: 7000
  recommendationservice:
    replicas: 1
    containerPort: 8080
    servicePort: 8080
    env:
      PRODUCT_CATALOG_SERVICE_ADDR: "productcatalogservice:3550"
      DISABLE_PROFILER: "1"
  checkoutservice:
    replicas: 1
    containerPort: 5050
    servicePort: 5050
  shippingservice:
    replicas: 1
    containerPort: 50051
    servicePort: 50051
  paymentservice:
    replicas: 1
    containerPort: 50051
    servicePort: 50051
  emailservice:
    replicas: 1
    containerPort: 8080
    servicePort: 5000        # checkout calls emailservice:5000
  adservice:
    replicas: 1
    containerPort: 9555
    servicePort: 9555
  redis-cart:
    replicas: 1
    containerPort: 6379
    servicePort: 6379
    image: redis:alpine      # not in Google's registry
  loadgenerator:
    replicas: 0              # keep 0 on 2 CPUs
    containerPort: 8089
    servicePort: 8089
    env:
      FRONTEND_ADDR: "frontend:80"
      USERS: "10"
      RATE: "1"